use crate::println;

#[repr(C)]
pub struct InterruptFrame {
    pub r15: u64,
    pub r14: u64,
    pub r13: u64,
    pub r12: u64,
    pub r11: u64,
    pub r10: u64,
    pub r9: u64,
    pub r8: u64,
    pub rdi: u64,
    pub rsi: u64,
    pub rbp: u64,
    pub rbx: u64,
    pub rdx: u64,
    pub rcx: u64,
    pub rax: u64,
    pub vector: u64,
    pub error_code: u64,
    pub rip: u64,
    pub cs: u64,
    pub rflags: u64,
    pub rsp: u64,
    pub ss: u64,
}

core::arch::global_asm!(
    ".global asm_exception_0",
    "asm_exception_0:",
    "push 0",
    "push 0",
    "jmp exception_common",
    ".global asm_exception_1",
    "asm_exception_1:",
    "push 0",
    "push 1",
    "jmp exception_common",
    ".global asm_exception_2",
    "asm_exception_2:",
    "push 0",
    "push 2",
    "jmp exception_common",
    ".global asm_exception_3",
    "asm_exception_3:",
    "push 0",
    "push 3",
    "jmp exception_common",
    ".global asm_exception_4",
    "asm_exception_4:",
    "push 0",
    "push 4",
    "jmp exception_common",
    ".global asm_exception_5",
    "asm_exception_5:",
    "push 0",
    "push 5",
    "jmp exception_common",
    ".global asm_exception_6",
    "asm_exception_6:",
    "push 0",
    "push 6",
    "jmp exception_common",
    ".global asm_exception_7",
    "asm_exception_7:",
    "push 0",
    "push 7",
    "jmp exception_common",
    ".global asm_exception_8",
    "asm_exception_8:",
    "push 8",
    "jmp exception_common",
    ".global asm_exception_9",
    "asm_exception_9:",
    "push 0",
    "push 9",
    "jmp exception_common",
    ".global asm_exception_10",
    "asm_exception_10:",
    "push 10",
    "jmp exception_common",
    ".global asm_exception_11",
    "asm_exception_11:",
    "push 11",
    "jmp exception_common",
    ".global asm_exception_12",
    "asm_exception_12:",
    "push 12",
    "jmp exception_common",
    ".global asm_exception_13",
    "asm_exception_13:",
    "push 13",
    "jmp exception_common",
    ".global asm_exception_14",
    "asm_exception_14:",
    "push 14",
    "jmp exception_common",
    ".global asm_exception_15",
    "asm_exception_15:",
    "push 0",
    "push 15",
    "jmp exception_common",
    ".global asm_exception_16",
    "asm_exception_16:",
    "push 0",
    "push 16",
    "jmp exception_common",
    ".global asm_exception_17",
    "asm_exception_17:",
    "push 17",
    "jmp exception_common",
    ".global asm_exception_18",
    "asm_exception_18:",
    "push 0",
    "push 18",
    "jmp exception_common",
    ".global asm_exception_19",
    "asm_exception_19:",
    "push 0",
    "push 19",
    "jmp exception_common",
    ".global asm_exception_20",
    "asm_exception_20:",
    "push 0",
    "push 20",
    "jmp exception_common",
    ".global asm_exception_21",
    "asm_exception_21:",
    "push 21",
    "jmp exception_common",
    ".global asm_exception_22",
    "asm_exception_22:",
    "push 0",
    "push 22",
    "jmp exception_common",
    ".global asm_exception_23",
    "asm_exception_23:",
    "push 0",
    "push 23",
    "jmp exception_common",
    ".global asm_exception_24",
    "asm_exception_24:",
    "push 0",
    "push 24",
    "jmp exception_common",
    ".global asm_exception_25",
    "asm_exception_25:",
    "push 0",
    "push 25",
    "jmp exception_common",
    ".global asm_exception_26",
    "asm_exception_26:",
    "push 0",
    "push 26",
    "jmp exception_common",
    ".global asm_exception_27",
    "asm_exception_27:",
    "push 0",
    "push 27",
    "jmp exception_common",
    ".global asm_exception_28",
    "asm_exception_28:",
    "push 0",
    "push 28",
    "jmp exception_common",
    ".global asm_exception_29",
    "asm_exception_29:",
    "push 29",
    "jmp exception_common",
    ".global asm_exception_30",
    "asm_exception_30:",
    "push 30",
    "jmp exception_common",
    ".global asm_exception_31",
    "asm_exception_31:",
    "push 0",
    "push 31",
    "jmp exception_common",
    "exception_common:",
    "push rax",
    "push rcx",
    "push rdx",
    "push rbx",
    "push rbp",
    "push rsi",
    "push rdi",
    "push r8",
    "push r9",
    "push r10",
    "push r11",
    "push r12",
    "push r13",
    "push r14",
    "push r15",
    "mov rdi, rsp",
    "call rust_exception_handler",
    "pop r15",
    "pop r14",
    "pop r13",
    "pop r12",
    "pop r11",
    "pop r10",
    "pop r9",
    "pop r8",
    "pop rdi",
    "pop rsi",
    "pop rbp",
    "pop rbx",
    "pop rdx",
    "pop rcx",
    "pop rax",
    "add rsp, 16",
    "iretq",
    ".global asm_exception_table",
    "asm_exception_table:",
    ".quad asm_exception_0",
    ".quad asm_exception_1",
    ".quad asm_exception_2",
    ".quad asm_exception_3",
    ".quad asm_exception_4",
    ".quad asm_exception_5",
    ".quad asm_exception_6",
    ".quad asm_exception_7",
    ".quad asm_exception_8",
    ".quad asm_exception_9",
    ".quad asm_exception_10",
    ".quad asm_exception_11",
    ".quad asm_exception_12",
    ".quad asm_exception_13",
    ".quad asm_exception_14",
    ".quad asm_exception_15",
    ".quad asm_exception_16",
    ".quad asm_exception_17",
    ".quad asm_exception_18",
    ".quad asm_exception_19",
    ".quad asm_exception_20",
    ".quad asm_exception_21",
    ".quad asm_exception_22",
    ".quad asm_exception_23",
    ".quad asm_exception_24",
    ".quad asm_exception_25",
    ".quad asm_exception_26",
    ".quad asm_exception_27",
    ".quad asm_exception_28",
    ".quad asm_exception_29",
    ".quad asm_exception_30",
    ".quad asm_exception_31",
);

extern "C" {
    static asm_exception_table: [u64; 32];
}

pub fn addr(vector: usize) -> usize {
    unsafe { asm_exception_table[vector] as usize }
}

#[no_mangle]
extern "C" fn rust_exception_handler(frame: *const InterruptFrame) {
    let f = unsafe { &*frame };
    if f.vector == 14 && f.cs & 3 == 3 {
        let fault = cr2();
        if crate::mem::Paging::cow_fault(crate::mem::Paging::cr3(), fault as usize) {
            return;
        }
    }
    let mode = if f.cs & 3 == 3 { "user" } else { "kernel" };
    println!(
        "EXCEPTION vec={} err={:#x} rip={:#x} cr2={:#x} mode={}",
        f.vector,
        f.error_code,
        f.rip,
        cr2(),
        mode
    );
    if f.cs & 3 == 3 {
        crate::Task::terminate();
        crate::Task::schedule();
    }
    loop {
        unsafe { core::arch::asm!("hlt", options(nomem, nostack)) }
    }
}

fn cr2() -> u64 {
    let v: u64;
    unsafe { core::arch::asm!("mov {0}, cr2", out(reg) v, options(nomem, nostack)) }
    v
}
